### ISSUE TITLE
ensure mongoose connection

### ISSUE THREAD

**Issue by liquid36** [lykmapipo/mongoose-gridfs#15]
Hello, 
Is it really necessary to ensure mongoose connection before use? I tried removing this lines [#L31](https://github.com/lykmapipo/mongoose-gridfs/blob/5268a75d1dd1bc6c71ec0705af38af3e9a4a656c/lib/storage.js#L31) and it worked perfectly. 

what inconvenience did you find without this lines? 

thanks

**Comment by lykmapipo** [comment]
@liquid36 Its not if you already initilized mongoose somewhere else
