### ISSUE TITLE
Refactoring of the code

### ISSUE THREAD

**Issue by rijkerd** [lykmapipo/mongoose-gridfs#21]
@lykmapipo can you please refactor your code into normal practice of creating a separate model file. It will make it easy for one to use it your code.

**Comment by lykmapipo** [comment]
@rijkerd I will appreciate a PR for that. Thanks for pointing out.

**Comment by lykmapipo** [comment]
@rijkerd Please see [https://github.com/lykmapipo/mongoose-gridfs/blob/master/lib/schema.js#L20](https://github.com/lykmapipo/mongoose-gridfs/blob/master/lib/schema.js#L20) its just a wrapper around [GridFS File Collection](https://docs.mongodb.com/manual/core/gridfs/#gridfs-files-collection)...we can start from them on refactoring....unless you have something specific on your side.

**Comment by rijkerd** [comment]
@lykmapipo Appreciated!!

**Comment by lykmapipo** [comment]
@rijkerd I will appreciate PR.
