### ISSUE TITLE
Add user ObjectId reference to attachment Schema

### ISSUE THREAD

**Issue by jorgecuevas92** [lykmapipo/mongoose-gridfs#22]
I've been tweaking and trying many different things to include a user property to an attachment but had no luck so far.

Is it possible to modify/extend the current schema for attachments so that I can relate it to the user?

**Comment by lykmapipo** [comment]
@jorgecuevas92 exposed schema is a mongoose schema definition for [MongoDB GridFS](https://docs.mongodb.com/manual/core/gridfs/). You can use [Metadata Field](https://docs.mongodb.com/manual/core/gridfs/#files.metadata)
