### ISSUE TITLE
Is it possible to change the GridFSSchema ?

### ISSUE THREAD

**Issue by etshy** [lykmapipo/mongoose-gridfs#29]
I have a File collection defined from Doctrine ODM examples
```
_id
name (filename)
mime
type (discriminator)
md5
length
filename (full path)
uploadDate
chunkSize
```

With the schema that is defined in const, I can't get/change my properties and have to change the schema so adding a way to change the schema could be good

**Comment by lykmapipo** [comment]
@etshy The schema is just a [mongoose schema](http://mongoosejs.com/docs/guide.html#definition) wrapper for [MongoDB GridFS File Collection](https://docs.mongodb.com/manual/core/gridfs/#gridfs-files-collection)...Consider saving more details on [metadata](https://docs.mongodb.com/manual/core/gridfs/#files.metadata)

**Comment by lykmapipo** [comment]
@etshy Also consider checking [https://github.com/lykmapipo/mongoose-gridfs#schema--model](https://github.com/lykmapipo/mongoose-gridfs#schema--model)

**Comment by etshy** [comment]
Oh true. i didn't know there was an example of gridFS doc, so I just followed the DoctrineODM example (as my main app is in PHP with symfony, I just have a little script in nodejs to make some little changes.)

But As my DoctrineDocument for files is already created and in use, I can't really change it now, but I'll think about that for my next project.

Also, I don't really see what you want to show on your docs ^^"

Once you get the Schema with `var AttachmentSchema = gridfs.schema;` can you change it to add some property ? I didn't saw things like that (I saw you can set some options though, but not property) and I'm quite a noob with nodeJS/mongoose (just started few days ago).

I'll take a look at all that when i can and return here to let you know if I managed to do what I want.

Thanks a lot.

**Comment by etshy** [comment]
In the end I just had to update  the file collection with a classic mongoose findAndUpdate to change the property like I want so all is good.
