### ISSUE TITLE
File with ID <xxxxxx> not opened for writing

### ISSUE THREAD

**Issue by Nop0x** [lykmapipo/mongoose-gridfs#30]
Hey there!

I'm using gridfs with mongoose and running into this error:

`"name":"MongoError","message":"file with id 5adfc7a99b0e190f7aa9cd0a not opened for writing","driver":true`

with this code:

```javascript
db.User.findById(obj.api_token, function (err, user) {
        db.Attachment.readById(user.picture.id, function (error, buffer) {
            if(buffer)
            {
                callback(null, buffer);
            }
            else
            {
                callback(error, null);
            }
        })
    });
```

I made sure the file itself exists in the database and is available.
Any idea how this happened?

Kind regards
Nop0x

**Comment by lykmapipo** [comment]
@Nop0x Not sure. May you please add your scenario on the specs.
