### ISSUE TITLE
Callback of write() never called

### ISSUE THREAD

**Issue by useo6** [lykmapipo/mongoose-gridfs#31]
Hi,
I'm having trouble with the write-callback. My schema/model is as follows:

```
const mongoose = require('mongoose')

const gridfs = require('mongoose-gridfs')({
  collection: 'attachments',
  model: 'Attachment',
  mongooseConnection: global.mongoConnection1
})

module.exports = global.mongoConnection1.model('Attachment', gridfs.schema)
```

In another file I use the gridfs-model:

```
const grifs = require('./gridfs.js')

gridfs.write({
  filename: 'myTestFile.ext',
  contentType: 'application/octet-stream'
}, fs.createReadStream('myTestFile.ext'), console.log)
```

Unfortunately, I see no output (console.log is never called). But the file is stored in my MongoDB database (I can see the entire data). Any suggestion why the callback of the write() operation is never called?

**Comment by useo6** [comment]
I figured out that the problem occurred because the done-callback in schema.js (line 83) is never called. But why do we need to read the file details again? I think they're already stored in the "createdFile" argument or not? II forked the repo, fixed it but I've not created any pull request because I'm not sure if I'm correct with my solution.

**Comment by foobst** [comment]
I'm having some more problems and I finally figured out what's wrong.
The problem is that mongoose.model() doesn't work when using mongoose.createConnection(). When I use global.mongoConnection1.model('Attachment').findById() in schema.js it works. So instead of using mongoose.model() everywhere it's necessary to use the connection specified during initialization (calling GridFSStorage). This can be achieved by using this.options.mongooseConnection.model() instead of mongoose.model(). I'll try to fix it on my fork.

**Comment by useo6** [comment]
I finally figured out the problem... The problem is that mongoose.model() doesn't work when using mongoose.createConnection(). When I use global.mongoConnection1.model('Attachment').findById() in schema.js it works. So instead of using mongoose.model() everywhere it's necessary to use the connection specified during initialization (calling GridFSStorage()). This can be achieved by using this.options.mongooseConnection.model() instead of mongoose.model(). I'll try to fix it on my fork.

**Comment by lykmapipo** [comment]
@useo6 On the `README` this has been mentioned. Sometimes you may need to ensure `mongoose connection` before use.

**Comment by useo6** [comment]
I fixed the issue on my own fork and it now works like a charme.

**Comment by lykmapipo** [comment]
@useo6 Sure. 

Regarding:
You can reproduce the problem when using `mongoose.createConnection()` instead of `mongoose.connect()`.

Lets have a spec that fail on using `mongoose.createConnection()`.

**Comment by useo6** [comment]
Regarding the spec... good question. We would need something like a timeout or similar because the callback isn't called.
