### ISSUE TITLE
Error installing npm-package via proxy

### ISSUE THREAD

**Issue by OlPavlov** [lykmapipo/mongoose-gridfs#32]
Hi.

I,ve faced a problem while installing via cntlm proxy.

Error message: "fatal: unable to access 'https://github.com/lykmapipo/gridfs-stream.git/': Unknown SSL protocol error in connection to github.com:443"

In "package-lock.json" file at line #538 I see this text:

"gridfs-stream": {
            "version": "git+https://github.com/lykmapipo/gridfs-stream.git#dd3c07d5c33264d1cbab9fc53a682a64e095bec4",
            "requires": {
                "flushwritable": "1.0.0"

Is it correct? It has no "resolved" key and URL in "version" key.

**Comment by lykmapipo** [comment]
@OlPavlov I had a patched [gridfs-stream](https://github.com/aheckmann/gridfs-stream) to make it work with latest mongoose stream api. I will publish the package to npm to avoid the issue.
