### ISSUE TITLE
warning GridStore is deprecated

### ISSUE THREAD

**Issue by lerit** [lykmapipo/mongoose-gridfs#34]
work fine,but warning below:
`DeprecationWarning: GridStore is deprecated, and will be removed in a future version. Please use GridFSBucket instead`

it throw from your custom gridfs-stream(writestream.js,line 64) package.
can you please fix this warning,thanks!

**Comment by qertis** [comment]
+1

**Comment by lykmapipo** [comment]
@lerit & @qertis I will work on the upgrade.

**Comment by quen2404** [comment]
@lerit & @qertis, i made this library in typescript if needed: [mongo-gridfs](https://www.npmjs.com/package/mongo-gridfs)

**Comment by romain10009** [comment]
@quen2404 how can I use this in the latest version of node? I don't think I can simply import it right?

**Comment by quen2404** [comment]
@romain10009 Yes you just have to import it as a standard JavaScript module 🙂

**Comment by romain10009** [comment]
@quen2404 I get the following error : "TypeError: MongoGridFS is not a constructor"

`
const MongoGridFS = require('mongo-gridfs');

let gridFS = new MongoGridFS(mongoose.connection.db, "fs");
`

**Comment by quen2404** [comment]
Can you open an issue in my project ? I will investigate

**Comment by MarcoSantarelli** [comment]
hi ,any solution do you ? ty
