### ISSUE TITLE
"close"-event fired too early?

### ISSUE THREAD

**Issue by mhombach** [lykmapipo/mongoose-gridfs#39]
I have an issue where the `close`-event is fired too early.

When i do this:
```js
readStream.on('data', (data) => { ... })
readStream.on('close', () => { ... })
```
and log the output, then my output looks like this:

```
data on readStream261120 index=56
data on readStream261120 index=57
data on readStream261120 index=58
close on readStream:
data on readStream169924 index=59
```
In my example my file has exactly 59 chunks.

Is this a known issue?
Please tell me, if you need more information on this or if you can't reproduce this issue.
Thanks in advance

**Comment by danilocasa** [comment]
I am experiencing the same issue.

**Comment by julioocamargoo** [comment]
That can be happening because the 'close' event was called before the 'data' event finish.

Take a look [here](https://stackoverflow.com/questions/32978094/nodejs-streams-and-premature-end).

Another detail is that probably you want to listen 'end' rather than 'close' event.

From NodeJS docs:

> The 'close' event is emitted when the stream and any of its underlying resources (a file descriptor, for example) have been closed. The event indicates that no more events will be emitted, and no further computation will occur.

> The 'end' event is emitted when there is no more data to be consumed from the stream.

**Comment by 720degreeLotus** [comment]
@julioocamargoo so we just need to listen to `end` instead of `close`? Ok that would be pretty easy (if you know it)...
