### ISSUE TITLE
readById metadata content-type

### ISSUE THREAD

**Issue by ivanhuay** [lykmapipo/mongoose-gridfs#4]
I am trying to do a search and return in addition to the image the metadata as the content-type but I do not find this functionality.

**Comment by lykmapipo** [comment]
@ivanhuay The `model` you obtain from `mongoose-gridfs` is actual mongoose model. Any mongoose query operations applies to it.

The special part is when you want to stream content from mongodb. This is when you have to use exposed `mongoose-gridfs` methods.

Hope it helps.

**Comment by ivanhuay** [comment]
I took some time to solve it because I had not noticed. Thank you very much
