### ISSUE TITLE
Passing base64 data coming as multi-part form data directly to Attachment.write

### ISSUE THREAD

**Issue by vikasgurjar** [lykmapipo/mongoose-gridfs#48]
I'm trying to directly write the file to mongo which comes as binary data from a Form. 

    ` const options = ({ filename: 'Test.png', contentType: 'image/png' });
            Attachment.write(options, req.body.file, (error, file) => {  // req.body.file is having binary data
                
                console.log(error, file);

            });`

is it possible? I don't want to store the file on the server, instead directly write it to mongo. Please guide me in the right direction.

**Comment by lykmapipo** [comment]
@vikasgurjar Sure you can store. if `req.body.file` is stream you are in the right track otherwise you have to convert it using library like [base64-stream](https://github.com/mazira/base64-stream) to stream and pass it.
