### ISSUE TITLE
Problem with connection

### ISSUE THREAD

**Issue by mts88** [lykmapipo/mongoose-gridfs#49]
Hello, I have a problem with connection and bucket. I create a model with `createModel({ connection: myMongooseConnection })`  but i have this error
```
Cannot read property 'collection' of undefined at new GridFSBucket
```
i found that variable `db` in `bucket.js`(line 589) is undefined. Any help?
Thanks.

**Comment by lykmapipo** [comment]
@mts88 Please ensure mongoose connection before call `createModel`

```js
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', () => {
 createModel(...)
});

```
