### ISSUE TITLE
[Discussion] plugin design

### ISSUE THREAD

**Issue by iBicha** [lykmapipo/mongoose-gridfs#6]
I was about to investigate how to make gridfs plugin for mongoose, when i found this.
What do you think about mongoose-gridfs as a plugin? with s usage similar to this:

```
var mongoose = require('mongoose');
var mongooseGridfs = require('mongoose-gridfs');

var UserSchema = mongoose.Schema({
    Name: {
        type: String,
        required: true
    },
    ProfilePicture: {
        type: mongooseGridfs.File
    }
});

UserSchema.plugin(mongooseGridfs);

var User = mongoose.model('User', UserSchema);

var user = new User();
user.Name = 'John Malkovich';
user.ProfilePicture = myFile; /* Stream | Buffer | String */
user.save(); /*To gridFs*/

user.ProfilePicture.stream(); /* Stream */
user.ProfilePicture.buffer(); /* Buffer */

```

Although it also makes sense to simply implement this for mongoose, as stated here:
https://github.com/Automattic/mongoose/issues/2631

I think still an interesting approach. One could just plug input from multi-part streams or buffers into the model instance, to later pipe the stream back through a router (if one is using express for example)

```
var express = require('express')
var multer  = require('multer')
var upload = multer()

var app = express()
//...
app.post('/:userId/profile', upload.single('avatar'), function (req, res, next) {
    req.user.ProfilePicture = req.file.buffer;
});
//...
app.post('/:userId/picture', function (req, res) {
    User.findById(req.params.userId, function(err, user){
        user.ProfilePicture.stream().pipe(res)
    });
});

```

**Comment by lykmapipo** [comment]
@iBicha It will be useful. I will review the codes and see what can be done.

Thanks.

**Comment by lykmapipo** [comment]
@iBicha I will appreciate PR for this feature. Please check [multer storage implementation](https://github.com/lykmapipo/mongoose-gridfs/blob/master/lib/storage.js#L290) which you can rely on if you want to link with express and multer.

**Comment by lykmapipo** [comment]
@iBicha So from your motivations..We will have to create a `SchemaType` that will point to `GridFS` collection per `model` or we should provide other abilities

Example
```js
const File = require('mongoose-gridfs').File;

const Book = new Schema({
  cover:{
      type: File,
     collection: 'covers' //or default to book_files
     ....other definition
   }
});
```

Please advice.

**Comment by iBicha** [comment]
Yeah, that's one approach to it, having a default "bucket", and all kind of default settings, and you can override options in the schema declaration, but an initial simple declaration would be

```
const File = require('mongoose-gridfs').File;
const Book = new Schema({
  cover:File
});
```
That's basically the suggested design in Automattic/mongoose#2631 which also follows the design of mongoose

I was planning to experiment with this but I got super busy, so I couldn't contribute much to the idea

**Comment by lykmapipo** [comment]
@iBicha Recently I have come across the same requirement. Once through with the work i will reafactor the codes as library and open it.

**Comment by iBicha** [comment]
Alright cool, thanks

**Comment by iBicha** [comment]
Will close for now. Feel free to reopen if still relevant.
