### ISSUE TITLE
.write() method returns null for err and file in callback

### ISSUE THREAD

**Issue by 4ty711** [lykmapipo/mongoose-gridfs#73]
Hi community,

I'm trying to write a file using the .write() method, But both arguments in the callback return null (err and file).

`Attachment.write({ ... }, fileData, (err, file) => {
   //err and file are both null
})`

The file I'm passing is a duplex.

All Versions of Mongoose, Mongo, and Node.js are the latest available.

Any help would be appreciated.

Thanks, 
Marco

**Comment by lykmapipo** [comment]
@4ty711 Please share sample snippets for us to reproduce the error for the fix.

**Comment by 4ty711** [comment]
@lykmapipo Thank you for your response!

The file is uploaded in express, using the express-fileupload plugin. It is then converted to stream.

Here is a piece of the code I'm using:

```javascript
var k = Object.keys(req.files)[0];
var file = req.files[k];

var stream = new Duplex();
stream.push(file.data);
stream.push(null);

Attachment.write({ _id: new mongoose.Types.ObjectId(), filename: "test"}, stream, (err, file) => {
    // err and file are null
}
```

**Comment by 4ty711** [comment]
Okay, the error has been resolved. Turned out that an error somewhere else in the code caused the issue. An empty stream was passed to the write method.

Thanks, @lykmapipo anyway!
